include:
  # https://docs.gitlab.com/ee/ci/yaml/index.html#includetemplate
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

deploystacks:
  trigger:
    include: .drupalci/.gitlab-single-pipeline.yml
    strategy: depend
  parallel:
    matrix:
      - DRUPAL_CORE_CONSTRAINT: ["9.3", "9.4"]
        PHP_VERSION: ["8.1", "8.0"]
        MYSQL_VERSION: ["8"]
        RRULE_CONSTRAINT: ["^2"]
      # RRULE library is fundamentally not compatible with PHP8.1.
      - DRUPAL_CORE_CONSTRAINT: ["9.3", "9.4"]
        PHP_VERSION: ["8.0"]
        MYSQL_VERSION: ["8"]
        RRULE_CONSTRAINT: ["^1"]
      # Drupal 10 requires PHP 8.1
      - DRUPAL_CORE_CONSTRAINT: ["10.0"]
        PHP_VERSION: ["8.1"]
        MYSQL_VERSION: ["8"]
        RRULE_CONSTRAINT: ["^2"]
