mysqldb:
  type: mariadb:10.3
  disk: 2048

# rediscache:
#   type: redis:5.0

# solrsearch:
#  type: solr:8.0
#  disk: 1024
#  configuration:
#    cores:
#      solr8core:
#        conf_dir: !archive "solr-conf/8.x"
#    endpoints:
#      solr:
#        core: solr8core
